FCPflow:
  #--------Define the model--------
  num_blocks: 6
  sfactor: 0.7
  hidden_dim: 64
  num_channels: 48 # resolution of the time series 
  condition_dim: 9 # unconditioned generation

  #--------Define the training--------  
  lr_min: 0.0001
  lr_max: 0.0005
  lr_step_size: 2000
  w_decay: 0.0
  batch_size: 2000

