FCPflow:
  #--------Define the model--------
  num_blocks: 8
  sfactor: 0.8
  hidden_dim: 24
  num_channels: 48 # resolution of the time series 
  condition_dim: 48 # unconditioned generation

  #--------Define the training--------  
  lr_min: 0.0001
  lr_max: 0.0005
  lr_step_size: 500
  w_decay: 0.0


